#!/usr/bin/env python3
"""
Database Backup Decryption Utility
----------------------------------
Decrypts encrypted SQLite backup packages (.zip.enc) generated by the Channel Cloner bot.

Usage:
    python scripts/decrypt_backup.py backup_file.zip.enc
    python scripts/decrypt_backup.py backup_file.zip.enc --extract
    python scripts/decrypt_backup.py backup_file.zip.enc --key "<your-encryption-key>"
"""

import os
import sys
import argparse
import base64
import hashlib
import zipfile
from pathlib import Path
import logging
logger = logging.getLogger(__name__)

# Add project root to sys.path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

try:
    from cryptography.fernet import Fernet
except ImportError:
    print("Error: 'cryptography' package is required. Install it using: pip install cryptography")
    sys.exit(1)


def get_cipher(custom_key: str = None) -> list:
    """Resolves potential decryption ciphers based on provided key, environment, or settings."""
    ciphers = []

    # 1. Custom key passed via CLI
    if custom_key:
        key_bytes = hashlib.sha256(custom_key.strip().encode("utf-8")).digest()
        ciphers.append(Fernet(base64.urlsafe_b64encode(key_bytes)))

    # 2. Try loading settings / .env
    try:
        from config.settings import settings
        if settings.ENCRYPTION_KEY:
            key_bytes = hashlib.sha256(settings.ENCRYPTION_KEY.encode("utf-8")).digest()
            ciphers.append(Fernet(base64.urlsafe_b64encode(key_bytes)))

        # Legacy cipher derived from BOT_TOKEN
        if settings.BOT_TOKEN:
            legacy_seed = f"{settings.BOT_TOKEN}:{settings.TELEGRAM_API_ID}:{settings.TELEGRAM_API_HASH}"
            legacy_key = hashlib.sha256(legacy_seed.encode("utf-8")).digest()
            ciphers.append(Fernet(base64.urlsafe_b64encode(legacy_key)))
    except Exception:
        logger.debug("Ignored exception", exc_info=True)

    # 3. Machine vault key file: VAULT_KEY_PATH (resolved like services/security_vault.py), then the default
    vault_paths = []
    try:
        from config.settings import settings
        configured = settings.VAULT_KEY_PATH or "database/.vault_key"
        vault_paths.append(Path(configured) if os.path.isabs(configured) else PROJECT_ROOT / configured)
    except Exception:
        logger.debug("Ignored exception", exc_info=True)
    default_vault_path = PROJECT_ROOT / "database" / ".vault_key"
    if default_vault_path not in vault_paths:
        vault_paths.append(default_vault_path)
    for vault_path in vault_paths:
        if not vault_path.exists():
            continue
        try:
            with open(vault_path, "r", encoding="utf-8") as f:
                disk_key = f.read().strip()
            if disk_key:
                key_bytes = hashlib.sha256(disk_key.encode("utf-8")).digest()
                ciphers.append(Fernet(base64.urlsafe_b64encode(key_bytes)))
        except Exception:
            logger.debug("Ignored exception", exc_info=True)

    return ciphers


def decrypt_backup(file_path: str, output_path: str = None, extract: bool = False, custom_key: str = None) -> bool:
    input_p = Path(file_path)
    if not input_p.exists():
        print(f"[-] Error: File not found: {file_path}")
        return False

    # Backward compatibility: Check if file is already a valid unencrypted ZIP archive
    if zipfile.is_zipfile(input_p):
        print(f"[i] File '{file_path}' is already a valid unencrypted ZIP archive. Skipping decryption.")
        if not output_path:
            output_path = str(input_p)
        elif output_path != str(input_p):
            import shutil
            shutil.copyfile(input_p, output_path)
            print(f"[+] ZIP archive saved to: {output_path}")

        if extract:
            extract_dir = input_p.parent / f"extracted_{input_p.stem}"
            extract_dir.mkdir(parents=True, exist_ok=True)
            try:
                with zipfile.ZipFile(input_p, "r") as zf:
                    zf.extractall(extract_dir)
                print(f"[+] Extracted database files to: {extract_dir}")
            except Exception as e:
                print(f"[-] Failed to extract zip: {e}")
                return False
        return True

    with open(input_p, "rb") as f:
        encrypted_data = f.read()

    ciphers = get_cipher(custom_key)
    if not ciphers:
        print("[-] Error: No encryption keys found in .env, the vault key file (VAULT_KEY_PATH), or --key.")
        return False

    decrypted_bytes = None
    for i, cipher in enumerate(ciphers):
        try:
            decrypted_bytes = cipher.decrypt(encrypted_data)
            print(f"[+] Decryption successful using candidate cipher #{i+1}")
            break
        except Exception:
            continue

    if decrypted_bytes is None:
        print("[-] Error: Failed to decrypt file. Invalid key or corrupt ciphertext.")
        return False

    # Determine output zip file path
    if not output_path:
        if input_p.suffix == ".enc":
            output_path = str(input_p.with_suffix(""))
        else:
            output_path = str(input_p.with_name(input_p.stem + "_decrypted.zip"))

    with open(output_path, "wb") as f:
        f.write(decrypted_bytes)
    print(f"[+] Decrypted ZIP archive saved to: {output_path}")

    if extract:
        extract_dir = input_p.parent / f"extracted_{input_p.stem}"
        extract_dir.mkdir(parents=True, exist_ok=True)
        try:
            with zipfile.ZipFile(output_path, "r") as zf:
                zf.extractall(extract_dir)
            print(f"[+] Extracted database files to: {extract_dir}")
        except Exception as e:
            print(f"[-] Failed to extract zip: {e}")

    return True


def main():
    parser = argparse.ArgumentParser(description="Decrypt Channel Cloner database backups.")
    parser.add_argument("file", help="Path to the encrypted backup (.zip.enc) file")
    parser.add_argument("-o", "--output", help="Optional output zip file path")
    parser.add_argument("-k", "--key", help="Explicit encryption key (if not in .env)")
    parser.add_argument("-x", "--extract", action="store_true", help="Automatically extract the zip contents")

    args = parser.parse_args()
    success = decrypt_backup(args.file, args.output, args.extract, args.key)
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
